language: elixir

otp_release:
  - 20
  - 21

elixir:
  - "1.7"
  - "1.8"

cache:
  directories:
  - _build
  - deps

script:
  - mix compile --warnings-as-errors
  - mix format --check-formatted
  - mix dialyzer --halt-exit-status
  - mix credo
  - mix coveralls.json

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

after_success:
  - bash <(curl -s https://codecov.io/bash)
